#!/bin/bash

export PYTHONUNBUFFERED=1

conda config --set show_channel_urls true
conda config --set add_pip_as_python_dependency false

conda update -n root --yes --quiet conda conda-build
conda install -n root --yes --quiet jinja2 anaconda-client

conda info
conda config --get
